### ISSUE TITLE
Implement client recovery methods

### ISSUE THREAD

**Issue by Farhad-Shabani** [informalsystems/sovereign-ibc#124]
## Summary

Implement the client recovery mechanism as part of the bigger effort outlined in [#2](https://github.com/informalsystems/sovereign-ibc/issues/2). 
This work includes:

```[tasklist]
### Tasks
- [X] Implement the `check_substitute` and `update_on_recovery` methods under the ICS02 `ClientStateCommon` trait
- [X] Integrate client recovery with CosmWasm client by adding a handler for the `MigrateClientStore` message type
- [X] Writing test to ensure CosmWasm client recovery happy path 
```
