### ISSUE TITLE
Tracking status of essential RPC methods 

### ISSUE THREAD

**Issue by Farhad-Shabani** [informalsystems/sovereign-ibc#126]
# Overview

This issue tracks the latest status and availability of the essential RPC methods required for integrating Hermes SDK in the 1st phase (high-priority endpoints) as outlined in the `DataRequirements.md` document. It also includes the link to their codebase for reference where you can see what **parameters each of these RPC methods accept or return**.

# RPC Methods

## Sequencer
- [X] [sequencer_publishBatch](https://github.com/informalsystems/sovereign-sdk-wip/blob/cfdec9397a7d8cb8c64d901b8b573b2160c7a3ed/full-node/sov-sequencer/src/lib.rs#L140-L155)
   - [ ] [Validate behaves according to expectations](https://github.com/Sovereign-Labs/sovereign-sdk-wip/issues/107)
- [X] [sequencer_acceptTx](https://github.com/informalsystems/sovereign-sdk-wip/blob/cfdec9397a7d8cb8c64d901b8b573b2160c7a3ed/full-node/sov-sequencer/src/lib.rs#L156-L167)
- [X] [sequencer_txStatus](https://github.com/informalsystems/sovereign-sdk-wip/blob/cfdec9397a7d8cb8c64d901b8b573b2160c7a3ed/full-node/sov-sequencer/src/lib.rs#L169-L177)

## Rollup (sov-ledger-rpc)
- [X] [ledger_getHead](https://github.com/informalsystems/sovereign-sdk-wip/blob/7d5595990c691e50d506e2b732b02b363d23ae36/full-node/sov-ledger-rpc/src/server.rs#L61-L68)
- [X] [ledger_getSlots](https://github.com/informalsystems/sovereign-sdk-wip/blob/7d5595990c691e50d506e2b732b02b363d23ae36/full-node/sov-ledger-rpc/src/server.rs#L71-L76)
- [X] [ledger_subscribeSlots](https://github.com/informalsystems/sovereign-sdk-wip/blob/7d5595990c691e50d506e2b732b02b363d23ae36/full-node/sov-ledger-rpc/src/server.rs#L205-L213)
- [X] [ledger_getEvents](https://github.com/informalsystems/sovereign-sdk-wip/blob/7d5595990c691e50d506e2b732b02b363d23ae36/full-node/sov-ledger-rpc/src/server.rs#L89-L93)
- [X] [ledger_getEventsByKey](https://github.com/informalsystems/sovereign-sdk-wip/blob/7d5595990c691e50d506e2b732b02b363d23ae36/full-node/sov-ledger-rpc/src/server.rs#L148-L154)
- [X] [ledger_getEventsByTxnHash](https://github.com/informalsystems/sovereign-sdk-wip/blob/7d5595990c691e50d506e2b732b02b363d23ae36/full-node/sov-ledger-rpc/src/server.rs#L141-L146)
- [X] [ledger_getTransactions](https://github.com/informalsystems/sovereign-sdk-wip/blob/7d5595990c691e50d506e2b732b02b363d23ae36/full-node/sov-ledger-rpc/src/server.rs#L83-L88)
- [X] [ledger_getTransactionsRange](https://github.com/informalsystems/sovereign-sdk-wip/blob/7d5595990c691e50d506e2b732b02b363d23ae36/full-node/sov-ledger-rpc/src/server.rs#L176-L181)
- [X] [ledger_getAggregatedProof](https://github.com/informalsystems/sovereign-sdk-wip/blob/7d5595990c691e50d506e2b732b02b363d23ae36/full-node/sov-ledger-rpc/src/server.rs#L199-L203): Returns latest
- [X] [ledger_getAggregatedProofInfo](https://github.com/informalsystems/sovereign-sdk-wip/blob/7d5595990c691e50d506e2b732b02b363d23ae36/full-node/sov-ledger-rpc/src/server.rs#L183-L197): Returns latest
- [X] [ledger_subscribeAggregatedProof](https://github.com/informalsystems/sovereign-sdk-wip/blob/7d5595990c691e50d506e2b732b02b363d23ae36/full-node/sov-ledger-rpc/src/server.rs#L215-L223)
- [ ] ledger_codeCommitment
- [X] [accounts_getAccount](https://github.com/informalsystems/sovereign-sdk-wip/blob/2bcb00f98dabbc8ce56abfe9babdfe5fb3979b7b/module-system/module-implementations/sov-accounts/src/rpc.rs#L23-L39)

## Rollup (sov-ibc)

- [X] ibc_moduleId
- [X] ibc_health

### Client
- [X] [ibc_clientState](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L59)
- [X] [ibc_clientStates](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L98)
- [X] [ibc_consensusState](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L112)
- [X] [ibc_consensusStates](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L171)
- [X] [ibc_consensusStateHeights](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L185)
- [X] [ibc_clientStatus](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L199)
- [X] [ibc_upgradedClientState](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L213)
- [X] [ibc_upgradedConsensusState](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L254)

### Connection

- [X] [ibc_connection](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L295)
- [X] [ibc_connections](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L309)
- [X] [ibc_clientConnections](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L323)
- [X] [ibc_connectionClientState](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L337)
- [X] [ibc_connectionConsensusState](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L351)
- [X] [ibc_connectionParams](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L365)

### Channel

- [X] [ibc_channel](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L379)
- [X] [ibc_channels](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L393)
- [X] [ibc_connectionChannels](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L407)
- [X] [ibc_channelClientState](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L421)
- [X] [ibc_channelConsensusState](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L435)
- [X] [ibc_packetCommitment](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L449)
- [X] [ibc_packetCommitments](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L484)
- [X] [ibc_packetReceipt](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L498)
- [X] [ibc_packetAcknowledgement](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L512)
- [X] [ibc_packetAcknowledgements](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L526)
- [X] [ibc_unreceivedPackets](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L540)
- [X] [ibc_unreceivedAcks](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L554)
- [X] [ibc_nextSequenceReceive](https://github.com/informalsystems/sovereign-ibc/blob/ee2f7d0ee175673dc2e0d3b98fe8182131bcb320/modules/sov-ibc/src/rpc/methods.rs#L568)

## Rollup (sov-ibc-transfer)

- [X] ibcTransfer_moduleId
- [X] ibcTransfer_health
- [X] [ibcTransfer_escrowedToken](https://github.com/informalsystems/sovereign-ibc/blob/f0481ed9336db1a0c9de55884dd4da8bc8949000/modules/sov-ibc-transfer/src/rpc.rs#L25)
- [X] [ibcTransfer_mintedToken](https://github.com/informalsystems/sovereign-ibc/blob/f0481ed9336db1a0c9de55884dd4da8bc8949000/modules/sov-ibc-transfer/src/rpc.rs#L43)
