### ISSUE TITLE
Integration tests for IBC relaying between Sovereign Rollups and Cosmos chains

### ISSUE THREAD

**Issue by Farhad-Shabani** [informalsystems/sovereign-ibc#26]
## Background
This issue tracks the implementation of essential integration tests (As outlined in the following task list) aimed at comprehensively covering various IBC relaying scenarios between Sovereign Rollups and Cosmos chains. These tests should be integrated into our CI pipeline to ensure their regular execution.

```[tasklist]
### Tasks
- [ ] https://github.com/informalsystems/sovereign-ibc/issues/5
```

To incorporate integration tests into CI, the following tasks must be completed first:

```[tasklist]
### Prerequisites
- [ ] https://github.com/informalsystems/sovereign-ibc/issues/19
- [ ] https://github.com/informalsystems/sovereign-ibc/issues/23
- [ ] https://github.com/informalsystems/sovereign-ibc/issues/24
- [ ] https://github.com/informalsystems/sovereign-ibc/issues/25
- [ ] https://github.com/informalsystems/sovereign-ibc/issues/40
- [ ] https://github.com/informalsystems/sovereign-ibc/issues/41
```
