### ISSUE TITLE
Empower Hermes to retrieve essential data from Sovereign SDK chains

### ISSUE THREAD

**Issue by Farhad-Shabani** [informalsystems/sovereign-ibc#32]
## Background

This tracking issue outlines necessary tasks for enabling Hermes to establish a seamless connection with a Sovereign SDK chain powered by Celestia. The objective is to identify / implement required RPC APIs (whether should be exposed by the **DA layer**, **rollup** or **sov-ibc** module) that will allow Hermes to access and retrieve specific datagrams essential for its relaying operations on Sovereign chains.

```[tasklist]
### Tasks
- [ ] https://github.com/informalsystems/sovereign-ibc/issues/3
- [ ] https://github.com/informalsystems/sovereign-ibc/issues/10
- [ ] https://github.com/informalsystems/sovereign-ibc/issues/29
- [ ] https://github.com/informalsystems/sovereign-ibc/issues/30
- [ ] https://github.com/informalsystems/sovereign-ibc/issues/31
```
